const CartActionTypes = {
  SHOW_CART: 'SHOW_CART',
  HIDDEN_CART: 'HIDDEN_CART',
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
};

export default CartActionTypes;
