const WishListActionTypes = {
  SHOW_WISHLIST: 'SHOW_WISHLIST',
  HIDDEN_WISHLIST: 'HIDDEN_WISHLIST',
  ADD_ITEM_TO_WISHLIST: 'ADD_ITEM_TO_WISHLIST',
  REMOVE_ITEM_FROM_WISHLIST: 'REMOVE_ITEM_FROM_WISHLIST',
  CLEAR_ITEM_FROM_WISHLIST: 'CLEAR_ITEM_FROM_WISHLIST',
  CLEAR_WISHLIST: 'CLEAR_WISHLIST',
};

export default WishListActionTypes;
