const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  SIGN_OUT: 'SIGN_OUT',

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_UPDATED_SUCCESS: 'REGISTER_UPDATED_SUCCESS',
  REGISTER_CREATED_SUCCESS: 'REGISTER_CREATED_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
};

export default UserActionTypes;
